### ISSUE TITLE
"view" instead of "send" with HW1

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1326]
The last rev where my HW1 properly works is : 7e0a80b697b7c79a24d0b5689a5686a4f23fbff5
After this, the send tx tab has only a view button and now way to actually send.
Signing messages still works.

**Comment by ecdsa** [comment]
did you enable the 'show before send' option in your preferences?

**Comment by ecdsa** [comment]
since 2.3.3, that option causes this behaviour. it is not related to HW1

**Comment by ulrichard** [comment]
Yes, that's correct. If I disable that option I can send.
But while it is enabled, I was unable to find a workflow that allowed me to send funds.
Is this a work in progress then?

**Comment by ecdsa** [comment]
after you sign, there should be a 'brodcast' button

**Comment by ulrichard** [comment]
Ah, the sign button on the tx detail dialog is missing with the HW1 wallet.

**Comment by ecdsa** [comment]
@btchip any idea?

**Comment by kyuupichan** [comment]
Just noting the results of our investigation: this is caused by the tx dialog's (in more than one place) calling tx.as_dict() which blows away the annotations added to the inputs by get_spendable_coins().

Arguably non-transaction class code shouldn't be setting the inputs in the TX.  Perhaps some separate annotation is better instead?  Or as_dict() should go to some length to preserve other fields....  Probably best for ThomasV to opine on what he thinks is the best way forwards here.

**Comment by ecdsa** [comment]
here is a quick fix: 5c2235e54bff91680c2d08b7722707688b0c426d
but I agree that it would be better to avoid side effects

**Comment by btchip** [comment]
I've merged the latest changes and get an exception before the transaction is displayed to be reviewed

```
Traceback (most recent call last):
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/gui/qt/main_window.py", line 1155, in do_send
    self.show_transaction(tx, tx_desc)
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/gui/qt/main_window.py", line 573, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/gui/qt/transaction_dialog.py", line 37, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/gui/qt/transaction_dialog.py", line 116, in __init__
    self.update()
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/gui/qt/transaction_dialog.py", line 167, in update
    tx_hash = self.tx.hash()
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/lib/transaction.py", line 676, in hash
    return Hash(self.raw.decode('hex') )[::-1].encode('hex')
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by ecdsa** [comment]
yes I saw that too

**Comment by ecdsa** [comment]
fixed in 994717318343b2674b9a08e4534cf18bd952173b

**Comment by ecdsa** [comment]
@ulrichard can you confirm that it's fixed?

**Comment by btchip** [comment]
I have pending commits for that - coming shortly

**Comment by btchip** [comment]
Issue with the latest version, same scenario

```
Traceback (most recent call last):
  File "/media/truecrypt1/work/oss/btchip/forks/electrum/gui/qt/transaction_dialog.py", line 150, in sign
    cancelled, ret = self.parent.sign_tx(self.tx, sign_done, parent=self)
TypeError: <lambda>() got an unexpected keyword argument 'parent'
```

**Comment by ecdsa** [comment]
sorry, I fixed that

**Comment by ulrichard** [comment]
I have still the same behavior with d3104a17b7043815f01d54dd947f7a32c563850d : No "sign" button on the tx window for the HW1 wallet if the review option is activated.

**Comment by btchip** [comment]
Should be fixed with this pull request if you add the referenced modification in lib/transaction.py (waiting for  @ecdsa to approve / commit it)

**Comment by btchip** [comment]
Everything has been merged - you should be able to retest from trunk

**Comment by ulrichard** [comment]
On the first try today I got error : "Invalid status 0e75" after loading the wallet and entering the pin.
But after that, everything worked nicely. The "sign" button appeared, I could sign my transaction and send the coins.
The second and third time I loaded the wallet the above error did not appear. So I guess the dongle was just in a wrong mode from earlier testing.
