### ISSUE TITLE
Cannot edit transaction description

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1435]
With the current git master, when I want to edit a transaction description, I get the following : 

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/history_widget.py", line 103, in <lambda>
    menu.addAction(_("Edit description"), lambda: self.edit_label(item))
AttributeError: 'HistoryWidget' object has no attribute 'edit_label'

**Comment by ecdsa** [comment]
broken by this commit :
851db130ea0ce779680d09c95967e6c55ac390a6

**Comment by kyuupichan** [comment]
Fixed by https://github.com/spesmilo/electrum/commit/0fa38074deea8ab4e07c9b948f0fea8a21dfae29 for editing by menu.  It might be easier to double-click or press F2.

**Comment by ulrichard** [comment]
Thanks for fixing it so quickly.

I just figured out that the same problem persists for editing labels of addresses and accounts.

**Comment by kyuupichan** [comment]
I've fixed that too
