### ISSUE TITLE
Electrum 2.5 doesn't sync

### ISSUE THREAD

**Issue by koteknik** [spesmilo/electrum#1517]
Hi,
This version of electrum isn't syncing with servers... result: no funds and all transaction are pending...
All previous versions where ok, it sometimes happened also, but restarting always soved it, not this time... if there is a solution or something to be done, please tell me! thx

**Comment by murder77** [comment]
probably manegament of topics of srver list (?) check this.

**Comment by gits7r** [comment]
Upgrade to 2.5.1 please. this has been fixed (the endless loop bug).

**Comment by koteknik** [comment]
Problem persists...
how to connect to other servers? I'm using the auto-connect, maybe it's a problem with server...; if I disable it it disconnects.

**Comment by ulrichard** [comment]
I'm not sure if it's the same problem, but I'm experiencing something similar on my workstation with the current git master head. On the notebook I don't have the problem with the same rev and the same wallet files.
When I start electrum, sometimes it just shows "Synchronizing..." and stays that way.
The easiest way is usually to load a wallet (-w cmdline option) that is out of date (needs to fetch new transactions). It will then update the GUI, and from there I can load wallets that would have the problem when loaded directly.

When the problem occurs, the terminal contains something like this : 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/richi/sourcecode/electrum/lib/network.py", line 750, in run
    self.wait_on_sockets()
  File "/home/richi/sourcecode/electrum/lib/network.py", line 739, in wait_on_sockets
    rout, wout, xout = select.select(rin, win, [], 0.1)
error: (4, 'Unterbrechung w\xc3\xa4hrend des Betriebssystemaufrufs')

"sni-qt/15426" WARN  22:58:59.113 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE

**Comment by kyuupichan** [comment]
Searching online this seems to be unique to Ubuntu and is perhaps because software on your system has version mismatches.

**Comment by ecdsa** [comment]
closing this; never encountered that bug.
