### ISSUE TITLE
Electrum 2.7.+ Freezes when trying to send payments

### ISSUE THREAD

**Issue by secondw123** [spesmilo/electrum#2016]
Hi,

Tried upgrading to each and every version from 2.7.0 to 2.7.11 when entering any amount for sending, Electrum freezes and eventually crashes (and can't be restarted in some cases, being closed upon launch):

http://imgur.com/a/RXKa7

Running win 8.1 and i find myself having to roll back to 2.6.4 over and over again.

Any idea why this happens or how to fix this? 

* Tried removing all files, installing the new version(s) and restoring from seed, still same issue.

**Comment by ecdsa** [comment]
do you have lots of small payments in your wallet?

**Comment by secondw123** [comment]
Hello!  I have several addresses (maybe 5) that have around 1000 small payment (in the 0.0X and 0.00X range) each out of dozens of other used that have big chunks of payments - total sum of the big payments is Waaayy more then the small ones.

This might be related?  Is there a possible solution to that?

**Comment by ecdsa** [comment]
can you email me your master public key, or publish it here?

**Comment by secondw123** [comment]
Hi, Mailed you the master public key to the email from your profile here electrumdev@

This is what you needed?

Really appreciate the help!

**Comment by ecdsa** [comment]
yes, thanks.

**Comment by secondw123** [comment]
Cool awaiting your reply

**Comment by ecdsa** [comment]
note: this wallet has more than 6k UTXOs

**Comment by secondw123** [comment]
What does it mean and what should i do about it?  Is it related to the issue?

**Comment by ecdsa** [comment]
it is related. I'm trying to figure out what's going on.

**Comment by secondw123** [comment]
Thanks awaiting your update.

**Comment by secondw123** [comment]
I tried sweeping the addresses with the many unspent tx and all i get is: "transaction rejected by the network rules (64x"

**Comment by ecdsa** [comment]
I figured out what the problem is; just did not have time to fix it yet

**Comment by secondw123** [comment]
Great news! so it should in the next update?

I have also fixed the 6000 utxo issue by consolidating everything. You think it will work now or its some other issue?

**Comment by ecdsa** [comment]
hi, can you resend me your master public key? 
sorry I did not keep your email..

**Comment by secondw123** [comment]
Hi! Mailed you the public key again to:   electrumdev @ etc...
Is this the correct mail?

**Comment by ecdsa** [comment]
yes, thanks!

**Comment by secondw123** [comment]
Cool, i'm more than happy to pay for a fix of this issue if this could support your resources?

**Comment by ecdsa** [comment]
note: the issue is that for loop in wallet.add_input_info() makes transaction creation cost quadratic

**Comment by secondw123** [comment]
And its fixed in 2.7.13 ?

**Comment by ecdsa** [comment]
no, didnt have time until now

**Comment by secondw123** [comment]
Bummer... guess i shall wait for next version :)

**Comment by ecdsa** [comment]
Your issue should be fixed in 63cff71f91f3c436ae4e33b9ee65fa7ef12986d8. Please let me know if it worked.
There are other inefficiencies revealed by the size of your wallet (more than 16k transactions), it took me a long time to restore from xpub. I opened #2094 for that.

**Comment by secondw123** [comment]
So is there a version i could download and test?  (2.7.13 still having this issue)

**Comment by ecdsa** [comment]
if you are on windows, wait for the next release.

**Comment by secondw123** [comment]
Awesome thanks! will do and update.

**Comment by secondw123** [comment]
Thanks 2.7.14 Working like a charm!!

**Comment by lastperson** [comment]
On 2.8.1, having 3000+ inputs to a single address results in that application works really slow. Signing a tx takes an hour.

**Comment by ecdsa** [comment]
signing is quadratic. 
do not create transactions with more than 100 inputs
