### ISSUE TITLE
Cannot open Electrum 2.7.12 on macOS 10.12.1 : wallet format requires update

### ISSUE THREAD

**Issue by zfox49** [spesmilo/electrum#2059]
Hi,
I'm sorry for my bad English. The problem as follow:
I download http://download.electrum.org/2.7.12/electrum-2.7.12.dmg and execute it. It print "Electrum Error", macOS Console print "BaseException: wallet format requires update".
Thus, I download source code and run it, Electrum print the same problem.
Thanks for your help.
```
Traceback (most recent call last):
  File "/Users/owo/miniconda2/envs/electrum/bin/electrum", line 4, in <module>
    __import__('pkg_resources').run_script('Electrum==2.7.12', 'electrum')
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/EGG-INFO/scripts/electrum", line 338, in <module>
    d.init_gui(config, plugins)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/daemon.py", line 253, in init_gui
    self.gui.main()
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum_gui/qt/__init__.py", line 204, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum_gui/qt/__init__.py", line 162, in start_new_window
    wallet = self.daemon.load_wallet(path)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/daemon.py", line 199, in load_wallet
    wallet = Wallet(storage)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/wallet.py", line 1709, in __new__
    wallet = WalletClass(storage)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/wallet.py", line 1610, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/wallet.py", line 1421, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/wallet.py", line 102, in __init__
    self.load_keystore()
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/wallet.py", line 1632, in load_keystore
    self.keystores[name] = load_keystore(self.storage, name)
  File "/Users/owo/miniconda2/envs/electrum/lib/python2.7/site-packages/Electrum-2.7.12-py2.7.egg/electrum/keystore.py", line 603, in load_keystore
    raise BaseException('wallet format requires update')
BaseException: wallet format requires update
```

**Comment by ecdsa** [comment]
hello; do you know if you have a standard wallet or another type?

**Comment by zfox49** [comment]
maybe BIP44 ? My wallet was recovery from Blockchains.info seed.

**Comment by ecdsa** [comment]
ok, in that case I suppose it is fixed by this commit 6020d72
I will do another release today

**Comment by ecdsa** [comment]
ok, I guess last release fixed it, right?

**Comment by zfox49** [comment]
Thank you...but the problem still...so I run `mv .electrum .electrumbak` and then recovery from Blockchains.info seed,It works.

**Comment by MsFloofie** [comment]
Hehe... Your username on your computer is OwO
