### ISSUE TITLE
v3 Error loading default wallet: "byte must be in range(0, 256)"

### ISSUE THREAD

**Issue by jonathancross** [spesmilo/electrum#3186]
Latest v3.0 binary for Mac OSx downloaded form electrum.org is failing for me on startup.
v2.9.2 was working fine with this wallet (only imported watch-only addresses).

![image](https://user-images.githubusercontent.com/5115470/32344462-3e6908fe-c007-11e7-83bb-a7c4c7ce3a3e.png)

Once I click "OK" the dialog closes without any useful error in the terminal.

If I rename `default_wallet` to something else, Electrum GUI will start.  If I then try to load the renamed wallet manually, I get a more useful error:
```
...
[WalletStorage] wallet path ~/.electrum/wallets/old_default_wallet
[profiler] load_transactions 0.0021
[profiler] build_reverse_history 0.0001
[profiler] save_transactions 0.0016
[profiler] check_history 0.0016
Traceback (most recent call last):
  File "electrum", line 373, in <module>
  File "Electrum-3.0-py3.6.egg/electrum/daemon.py", line 291, in init_gui
  File "Electrum-3.0-py3.6.egg/electrum_gui/qt/__init__.py", line 247, in main
  File "Electrum-3.0-py3.6.egg/electrum_gui/qt/__init__.py", line 206, in start_new_window
  File "Electrum-3.0-py3.6.egg/electrum/wallet.py", line 963, in start_threads
  File "Electrum-3.0-py3.6.egg/electrum/synchronizer.py", line 58, in __init__
  File "Electrum-3.0-py3.6.egg/electrum/synchronizer.py", line 184, in initialize
  File "Electrum-3.0-py3.6.egg/electrum/synchronizer.py", line 81, in subscribe_to_addresses
  File "Electrum-3.0-py3.6.egg/electrum/network.py", line 636, in subscribe_to_addresses
  File "Electrum-3.0-py3.6.egg/electrum/network.py", line 636, in <listcomp>
  File "Electrum-3.0-py3.6.egg/electrum/network.py", line 621, in addr_to_scripthash
  File "Electrum-3.0-py3.6.egg/electrum/bitcoin.py", line 418, in address_to_scripthash
  File "Electrum-3.0-py3.6.egg/electrum/bitcoin.py", line 404, in address_to_script
  File "Electrum-3.0-py3.6.egg/electrum/bitcoin.py", line 337, in b58_address_to_hash160
  File "Electrum-3.0-py3.6.egg/electrum/bitcoin.py", line 482, in base_decode
ValueError: byte must be in range(0, 256)
[33785] Failed to execute script electrum
[Plugins] stopped
[Network] stopping network
[Network] stopped
[Daemon] shutting down network
[Daemon] stopped
```

I took a look in this particular wallet and identified an item in the `addresses` this field as causing the issue:
```
    "addresses": {
        "#foo-label": null
    },
```
Seems that a previous wallet version somehow allowed the creation of this nonsense "address" and the app is trying to decode it as a bitcoin address.  I suspect the change causing this issue may have been introduced here: e8b564c0e728e1ca15d39f48a0153c984e2acc3c

**Note:** a different `null` "address" didn't have the `#` prefix, resulting in a different error dialog: _'NoneType' object is not subscriptable_ :
![screen shot 2017-11-03 at 12 27 11 am](https://user-images.githubusercontent.com/5115470/32355298-280bf3f6-c02e-11e7-82fe-37e0db3fcb09.png)

**Comment by ecdsa** [comment]
@jonathancross that should be fixed with 3.0.1

**Comment by jonathancross** [comment]
Still getting the same errors with the 3.0.1 release.
Here is example of malformed wallet addresses that triggers the errors shown above:
```
    "addresses": {
        "#4": null,
        "foo": null,
```
_... normal, valid addresses follow._

**Comment by jonathancross** [comment]
Nevermind, it is working now, thanks!

Explanation: I had to manually rollback `"seed_version"` to `15`, then it triggered the "upgrade" to 16 and the junk address removal. Probably a side effect of testing broken address formats got me to version 16 somehow.
