### ISSUE TITLE
signing message fails with error "string argument without encoding" on ubuntu

### ISSUE THREAD

**Issue by Cerv4ntez** [spesmilo/electrum#3211]
Using electrum 3 with leder nano s on ubuntu 17.10, signing a message fails with the error message "string argument without encoding".
![screenshot from 2017-11-04 07-04-23](https://user-images.githubusercontent.com/18594385/32402914-6c15dc32-c12e-11e7-9fa5-43d1505c65e9.png)

when closing the dialog and retrying the error changes to "wrapped c/c++ object of type WindowModalDialog has been deleted"
![screenshot from 2017-11-04 07-03-15](https://user-images.githubusercontent.com/18594385/32402904-469f4ba0-c12e-11e7-993d-a950f99c165b.png)

**Comment by SomberNight** [comment]
Could you try to start Electrum with the `-v` option, and give the associated stack traces (if they are printed)?

**Comment by Cerv4ntez** [comment]
There you go:

string argument without an encoding
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/ledger/ledger.py", line 230, in sign_message
    info = self.get_client().signMessagePrepare(address_path, message)
  File "/usr/local/lib/python3.6/dist-packages/btchip/btchip.py", line 451, in signMessagePrepare
    result = self.signMessagePrepareV2(path, message)
  File "/usr/local/lib/python3.6/dist-packages/btchip/btchip.py", line 433, in signMessagePrepareV2
    params.extend(bytearray(message[offset : offset + dataLength]))
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/util.py", line 581, in run
    result = task.task()
  File "/usr/local/lib/python3.6/dist-packages/electrum/wallet.py", line 1344, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/ledger/ledger.py", line 247, in sign_message
    self.give_error(e, True)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/ledger/ledger.py", line 211, in give_error
    raise Exception(message)
Exception: string argument without an encoding

**Comment by ecdsa** [comment]
@btchip this requires an additional patch for btchip-python:
`
diff --git a/btchip/btchip.py b/btchip/btchip.py
index 3f4dafd..b471319 100644
--- a/btchip/btchip.py
+++ b/btchip/btchip.py
@@ -415,7 +415,7 @@ class btchip:
                        self.resolvePublicKeysInPath(path)                              
                result = {}
                offset = 0
-               encryptedOutputData = ""
+               encryptedOutputData = bytearray()
                while (offset < len(message)):
                        params = [];
                        if offset == 0:
`

**Comment by Cerv4ntez** [comment]
hi i replaced the line in the file mentioned by the stacktrace but it did not change this behaviour. were you able to reproduce the issue on your end and did this fix it for you?

**Comment by laszlomakk** [comment]
> this requires an additional patch for btchip-python

meaning it won't work until a future release of that library

**Comment by Cerv4ntez** [comment]
Oh, ok now i understand, thanks for clearing that up
 

Gesendet: Sonntag, 05. November 2017 um 19:13 Uhr
Von: "Laszlo Makk" <notifications@github.com>
An: spesmilo/electrum <electrum@noreply.github.com>
Cc: Cerv4ntez <WIRED79@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [spesmilo/electrum] signing message fails with error "string argument without encoding" on ubuntu (#3211)



this requires an additional patch for btchip-python


meaning it won't work until a future release of that library

**Comment by btchip** [comment]
Fixed in 0.1.22

**Comment by Cerv4ntez** [comment]
Hi again, i upgraded to 0.1.22 but still get the same errors, and stack trace seems the same:
string argument without an encoding
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/ledger/ledger.py", line 230, in sign_message
    info = self.get_client().signMessagePrepare(address_path, message)
  File "/usr/local/lib/python3.6/dist-packages/btchip/btchip.py", line 451, in signMessagePrepare
    result = self.signMessagePrepareV2(path, message)
  File "/usr/local/lib/python3.6/dist-packages/btchip/btchip.py", line 433, in signMessagePrepareV2
    params.extend(bytearray(message[offset : offset + dataLength]))
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum_gui/qt/util.py", line 581, in run
    result = task.task()
  File "/usr/local/lib/python3.6/dist-packages/electrum/wallet.py", line 1344, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/ledger/ledger.py", line 247, in sign_message
    self.give_error(e, True)
  File "/usr/local/lib/python3.6/dist-packages/electrum_plugins/ledger/ledger.py", line 211, in give_error
    raise Exception(message)

**Comment by ecdsa** [comment]
because you did not install the upgrade with python3 ?

**Comment by SomberNight** [comment]
You also need to be on Electrum master. 3.0.0 does not contain the fix.

**Comment by ecdsa** [comment]
or use 3.0.1 :)

**Comment by Cerv4ntez** [comment]
is it possible that the 3.0.1 tarball is incomplete? installing it using pip3 results in the binary being non-executable, and, after making it executable, giving me an error:
electrum
cannot import name 'icons_rc'
Error: Could not find icons file.
Please run 'pyrcc5 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum

when i tried to do that, i found that  gui/qt/icons_rc.py was missing

i then went ahead and downloaded the master zip, but doing python3 setup.py install resulted in:
electrum -v
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 4, in <module>
    __import__('pkg_resources').run_script('Electrum==3.0.1', 'electrum')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'electrum'

**Comment by ecdsa** [comment]
which tarball did you download?
the tarball from github is incomplete, yes.
you should use the one on electrum.org

**Comment by Cerv4ntez** [comment]
ok thanks, i managed to start electrum directly from the directory i unpacked the electrum-master.zip from the github page and was able to sign my message, thank you all for your assistance
