### ISSUE TITLE
Not prompted to set password when creating imported private key wallet

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#3295]
When you create a wallet using imported private keys you are not prompted to set a password during the wallet creation process. Tested in 3.0.1.

(WIF private keys not xprvs. You are prompted when creating a wallet with xprvs)

**Comment by SomberNight** [comment]
"bug A" should be solved on master now, due to https://github.com/spesmilo/electrum/pull/3346

I haven't tested the others recently, but I did back when the issue was opened, they are probably still TODOs.

**Comment by AbdussamadA** [comment]
Thanks! The other two bugs are still there in 3.0.6. I'm going to name the last one bug c so it's clearer.
