### ISSUE TITLE
sending invalid commitment

### ISSUE THREAD

**Issue by ysangkok** [spesmilo/electrum#5110]
since e23c7de7cc0652414ba46a8f2c6014b994887be8 (also verified this bug on 1e6986bd6c34d7d43acdd21a32a6a2845c47404c), if i open a channel with 0.15 btc and send 10000 sat, I get the following in the lnd console

```
2019-02-12 14:43:07.578 [ERR] HSWC: ChannelLink(5338:1:0) Failing link: 
ChannelPoint(d5b2ae4fe1216133cc5f1aed31fbaf083ad2b000c0b3bb3f4d32a49e4bf0bf3b:0): unable to accept new commitment: rejected commitment: 
commit_height=2, 
invalid_commit_sig=3045022100ac8bab94dc4bae2e045bbd8d669b5889de57b19df4689732dfb7afbc9f1490940220170d05d31ac01721d2cedcdd9ab94a5f0f2c812fcb9ee9e02daaf82c0a7a7519, 
commit_tx=02000000013bbff04b9ea4324d3fbbb3c000b0d23a08affb31ed1a5fcc336121e14faeb2d50000000000ee9c3780016c3be400000000001600147a331d79e5bee380588cf3d71ab5f4d351328dfab5c67e20, 
sig_hash=68a46cb188e3637af792817d60f5ad9805dbd4fa429524e1ea4f21f696a9e4ad
```

**Comment by ysangkok** [comment]
We are sending a commitment right after they settle, that makes little sense to me since according to spec "the node only adds those updates to its own commitment transaction when the remote node acknowledges it has applied them via revoke_and_ack.".

So sending "commitment_signed" at this point is bad because we cannot include the removal of the HTLC (it was added in ctn 1, removed in 2), and we can't send a "commitment_signed" with no changes either.

**Comment by ysangkok** [comment]
It is unclear for me what `self.pending_updates` refers to. For example, if we receive a settlement, we can't send the commitment as mentioned in my previous comment. But an update is still pending.

**Comment by ecdsa** [comment]
should be fixed in ad73f451abd69e4079e14d5354b64a42b0c789bb

**Comment by ysangkok** [comment]
just tested on 8ebe69b9741d0155d0300e1617e1934609aeb167, still broken

**Comment by ysangkok** [comment]
i applied this patch 

```
diff --git a/electrum/lnpeer.py b/electrum/lnpeer.py
index 4803fb881..c644dbd75 100644
--- a/electrum/lnpeer.py
+++ b/electrum/lnpeer.py
@@ -824,7 +824,7 @@ class Peer(PrintError):
     def maybe_send_commitment(self, chan: Channel):
         if not self.local_pending_updates[chan] and not self.remote_pending_updates[chan]:
             return
-        self.print_error('send_commitment')
+        self.print_error('send_commitment', self.local_pending_updates[chan], self.remote_pending_updates[chan])
         sig_64, htlc_sigs = chan.sign_next_commitment()
         self.send_message("commitment_signed", channel_id=chan.channel_id, signature=sig_64, num_htlcs=len(htlc_sigs), htlc_signature=b"".join(htlc_sigs))
         self.local_pending_updates[chan] = False
```

and note that the output is

```
[Channel][lnchannel_2bee5897] receive_htlc_settle
[Peer][localhost:9735] send_commitment True False
```

I think it's wrong to only refrain from sending the commitment when both sides have updates pending. The commitment should be sent as soon as updates are pending for the remote node, which would be the case after we have acked the commitment they send us after the "receive_htlc_settle". Of course it depends on the direction of the HTLC which side is it pending for first.

**Comment by ysangkok** [comment]
eclair uses the following function definition, note how `remoteHasChanges` is dependent on `localChanges` that have been acked (by us, presumably), or `remoteChanges` that have been proposed (by us). So by using this model, since they sent the `update_fulfill`, `remoteHasChanges`  would be false since the change (settlement) is contained in `localChanges` (where also the htlc resides, just like in our model currently), but since it hasn't been acked yet (we would only ack it after processing their commitment), it wouldn't trigger `remoteHasChanges`.

https://github.com/ACINQ/eclair/blob/3aa57544903287a7902abc53b227223cfcacd057/eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala#L352-L355

**Comment by ecdsa** [comment]
I believe this is fixed now
