### ISSUE TITLE
Missing History. "Error: history not synchronized"

### ISSUE THREAD

**Issue by VNBM** [spesmilo/electrum#5444]
The entire section of the History tab is now blank.

It was all showing previously as it should. I had a payment being sent that was not confirmed so I was increasing the fee.  After broadcasting the transaction to increase the fee, the entire history section went blank.

The balance of the wallet still shows but no history.  I only have 1 wallet and have made no changes to any of the settings that would effect the showing of history, the only thing I did was increase the fee, literally nothing else.

**Comment by SomberNight** [comment]
What version of Electrum? Please make sure it is the latest.
Enable [debug logging](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging) and see if there is anything interesting. Please consider uploading the log.

Your wallet file / history likely got corrupted somehow; you can restore from seed words to fix this.
Running `wallet.clear_history()` in the `Console` tab and then restarting the application might also work.

**Comment by VNBM** [comment]
It is the latest version, 3.3.6.

Restoring did nothing. Still no history. It was there one second, and as soon as I increased the fee, it went blank.

**Comment by SomberNight** [comment]
Please upload debug logs.

**Comment by VNBM** [comment]
3.3.6 is not showing me the debug info as previous versions and I'm not able to locate instruction online on how to locate it. Would you be able to advise on how I can obtain those to upload them?

**Comment by VNBM** [comment]
Hope this is the information you are requesting:

20190626T050632.047761Z |     INFO | logging | Electrum version: 3.3.6 - https://electrum.org - https://github.com/spesmilo/electrum
20190626T050632.047761Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.17134-SP0
20190626T050632.047761Z |     INFO | logging | Logging to file: C:\Users\Will\AppData\Roaming\Electrum\logs\electrum_log_20190626T050632Z_9888.log
20190626T050632.047761Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20190626T050633.053073Z |     INFO | daemon | failed to connect to JSON-RPC server: [WinError 10061] No connection could be made because the target machine actively refused it
20190626T050633.058061Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20190626T050633.061051Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20190626T050633.068032Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20190626T050633.072022Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20190626T050633.077009Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20190626T050633.078007Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20190626T050633.080999Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20190626T050633.082994Z |    DEBUG | util.profiler | Plugins.__init__ 0.0289
20190626T050633.090971Z |     INFO | network | blockchains [0]
20190626T050633.092967Z |     INFO | exchange_rate.FxThread | using exchange BitcoinAverage
20190626T050633.092967Z |     INFO | network | starting network
20190626T050633.093964Z |     INFO | network | connecting to electrum.lightning.supplies:50002:s as new interface
20190626T050633.095960Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T050633.099947Z |    DEBUG | util.profiler | Daemon.__init__ 0.0170
20190626T050633.455995Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20190626T050633.753201Z |     INFO | interface.[hsmiths4fyqlw5xw.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050633.754199Z |     INFO | interface.[electrumx.ftp.sh:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050633.754199Z |     INFO | network | couldn't launch iface hsmiths4fyqlw5xw.onion:50002:s -- CancelledError()
20190626T050633.754199Z |     INFO | network | couldn't launch iface electrumx.ftp.sh:50002:s -- CancelledError()
20190626T050633.791098Z |     INFO | interface.[bauerjda5hnedjam.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050633.792095Z |     INFO | network | couldn't launch iface bauerjda5hnedjam.onion:50002:s -- CancelledError()
20190626T050633.876869Z |     INFO | interface.[electrum.lightning.supplies:50002] | connection established. version: ['ElectrumX 1.10.1', '1.4']
20190626T050633.936709Z |     INFO | interface.[electrum.lightning.supplies:50002] | set blockchain with height 581997
20190626T050633.937706Z |     INFO | interface.[electrum.lightning.supplies:50002] | can't connect 582481
20190626T050633.937706Z |     INFO | interface.[electrum.lightning.supplies:50002] | requesting block header 581998 in mode backward
20190626T050633.938704Z |     INFO | network | switching to electrum.lightning.supplies:50002:s
20190626T050634.294750Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.8358
20190626T050634.295748Z |     INFO | storage.WalletStorage | wallet path c:\users\will\appdata\roaming\electrum\wallets\default_wallet
20190626T050634.310707Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T050634.311705Z |     INFO | interface.[vmd30612.contaboserver.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050634.312703Z |     INFO | network | couldn't launch iface vmd30612.contaboserver.net:50002:s -- CancelledError()
20190626T050634.314698Z |     INFO | interface.[electrum.lightning.supplies:50002] | exiting backward mode at 581998
20190626T050634.323674Z |     INFO | interface.[electrum.lightning.supplies:50002] | could connect 581998
20190626T050634.771476Z |     INFO | interface.[electrum.lightning.supplies:50002] | requesting chunk from height 581999
20190626T050634.775465Z |     INFO | network | fee_histogram [[112, 100694], [96, 116802], [92, 173613], [90, 181644], [82, 39804], [15, 161664], [6, 1507868], [5, 879228], [4, 649553], [3, 992046], [2, 1137129], [1, 3407287]]
20190626T050634.775465Z |     INFO | network | fee_estimates {25: 37916, 10: 86991, 5: 91633, 2: 91633}
20190626T050634.788431Z |     INFO | interface.[VPS.hsmiths.com:50002] | disconnecting due to: ConnectionRefusedError(10061, "Connect call failed ('127.0.0.127', 50002)")
20190626T050634.791424Z |     INFO | network | couldn't launch iface VPS.hsmiths.com:50002:s -- CancelledError()
20190626T050634.812367Z |     INFO | storage.WalletStorage | wallet path c:\users\will\appdata\roaming\electrum\wallets\default_wallet
20190626T050634.813365Z |     INFO | storage.WalletStorage | wallet path c:\users\will\appdata\roaming\electrum\wallets\default_wallet
20190626T050634.903125Z |     INFO | interface.[bitcoin3nqy3db7c.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050634.903125Z |     INFO | network | couldn't launch iface bitcoin3nqy3db7c.onion:50002:s -- CancelledError()
20190626T050635.504516Z |     INFO | interface.[electrum3.hodlister.co:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20190626T050635.510499Z |     INFO | interface.[electrum-unlimited.criptolayer.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionRefusedError(10061, "Connect call failed ('188.40.93.205', 50002)"),)
20190626T050635.511497Z |     INFO | network | couldn't launch iface electrum-unlimited.criptolayer.net:50002:s -- CancelledError()
20190626T050635.706974Z |     INFO | interface.[electrum3.hodlister.co:50002] | set blockchain with height 582481
20190626T050635.707971Z |     INFO | interface.[electrum3.hodlister.co:50002] | skipping header 582481
20190626T050635.860562Z |     INFO | interface.[electrumx.ml:50002] | connection established. version: ['ElectrumX 1.8.12', '1.4']
20190626T050635.929378Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | connection established. version: ['ElectrumX 1.8.12', '1.4']
20190626T050635.980242Z |     INFO | interface.[wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050635.980242Z |     INFO | network | couldn't launch iface wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002:s -- CancelledError()
20190626T050636.127848Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | set blockchain with height 582481
20190626T050636.128845Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | skipping header 582481
20190626T050636.263486Z |     INFO | interface.[thanos.xskyx.net:50002] | connection established. version: ['ElectrumX 1.12', '1.4']
20190626T050636.446995Z |     INFO | interface.[thanos.xskyx.net:50002] | set blockchain with height 582481
20190626T050636.447992Z |     INFO | interface.[thanos.xskyx.net:50002] | skipping header 582481
20190626T050636.574651Z |     INFO | interface.[electrumx.ml:50002] | set blockchain with height 582481
20190626T050636.574651Z |     INFO | interface.[electrumx.ml:50002] | skipping header 582481
20190626T050637.530097Z |     INFO | interface.[electrum.nute.net:17315] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20190626T050637.541068Z |     INFO | interface.[e10.keff.org:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20190626T050637.734550Z |     INFO | interface.[electrum.nute.net:17315] | set blockchain with height 582481
20190626T050637.735548Z |     INFO | interface.[electrum.nute.net:17315] | skipping header 582481
20190626T050637.767473Z |     INFO | interface.[e10.keff.org:50002] | set blockchain with height 582481
20190626T050637.768459Z |     INFO | interface.[e10.keff.org:50002] | skipping header 582481
20190626T050639.132811Z |    DEBUG | util.profiler | JsonDB.load_transactions 0.0000
20190626T050639.140788Z |    DEBUG | util.profiler | AddressSynchronizer.load_local_history 0.0010
20190626T050639.140788Z |    DEBUG | util.profiler | AddressSynchronizer.check_history 0.0000
20190626T050639.330282Z |    DEBUG | util.profiler | WalletStorage.write 0.0000
20190626T050639.538724Z |    DEBUG | util.profiler | Deterministic_Wallet.try_detecting_internal_addresses_corruption 0.1197
20190626T050639.538724Z |    DEBUG | util.profiler | ElectrumWindow.load_wallet 0.1646
20190626T050639.587593Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20190626T050639.588592Z |     INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
20190626T050639.588592Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0010
20190626T050639.588592Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0010
20190626T050641.035719Z |     INFO | gui.qt.update_checker.UpdateCheckThread | valid sig for version announcement '3.3.6' from address '13xjmVAB1EATPP8RshTE8S8sNwwSUM9p1P'
20190626T050654.777297Z |     INFO | interface.[81-7-10-251.blue.kundencontroller.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('81.7.10.251', 50002)"),)
20190626T050654.777297Z |     INFO | network | couldn't launch iface 81-7-10-251.blue.kundencontroller.de:50002:s -- CancelledError()
20190626T050655.837744Z |     INFO | interface.[b.ooze.cc:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2001:41d0:800:6cf::', 50002, 0, 0), [Errno 10060] Connect call failed ('145.239.252.207', 50002)",),)
20190626T050655.837744Z |     INFO | network | couldn't launch iface b.ooze.cc:50002:s -- CancelledError()
20190626T050657.234035Z |     INFO | interface.[dragon085.startdedicated.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('69.64.46.27', 50002)"),)
20190626T050657.234035Z |     INFO | network | couldn't launch iface dragon085.startdedicated.de:50002:s -- CancelledError()
20190626T050657.403557Z |     INFO | interface.[electrum.leblancnet.us:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionRefusedError(10061, "Connect call failed ('205.197.210.30', 50002)"),)
20190626T050657.404556Z |     INFO | network | couldn't launch iface electrum.leblancnet.us:50002:s -- CancelledError()
20190626T050659.337384Z |     INFO | interface.[bitcoins.sk:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionRefusedError(10061, "Connect call failed ('46.229.238.187', 50002)"),)
20190626T050659.338382Z |     INFO | network | couldn't launch iface bitcoins.sk:50002:s -- CancelledError()
20190626T050701.448759Z |     INFO | interface.[daedalus.bauerj.eu:50002] | disconnecting due to: ConnectionRefusedError(10061, "Connect call failed ('151.80.161.244', 50002)")
20190626T050701.449734Z |     INFO | network | couldn't launch iface daedalus.bauerj.eu:50002:s -- CancelledError()
20190626T050715.929743Z |     INFO | interface.[62.210.107.208:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('62.210.107.208', 50002)"),)
20190626T050715.929743Z |     INFO | network | couldn't launch iface 62.210.107.208:50002:s -- CancelledError()
20190626T050717.493585Z |     INFO | interface.[77.20.219.157:50001] | succeeded in getting cert
20190626T050718.650462Z |     INFO | interface.[technetium.network:50002] | disconnecting due to: TimeoutError(10060, "Connect call failed ('96.27.19.205', 50002)")
20190626T050718.651365Z |     INFO | network | couldn't launch iface technetium.network:50002:s -- CancelledError()
20190626T050719.752215Z |     INFO | interface.[77.20.219.157:50001] | connection established. version: ['ElectrumX 1.11.0', '1.4']
20190626T050720.573303Z |     INFO | interface.[77.20.219.157:50001] | set blockchain with height 582481
20190626T050720.573303Z |     INFO | interface.[77.20.219.157:50001] | skipping header 582481
20190626T050721.306395Z |     INFO | interface.[electrum.nute.net:17315] | could connect 582482
20190626T050721.355196Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20190626T050721.356195Z |     INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
20190626T050721.356195Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0010
20190626T050721.356195Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0010
20190626T050722.209755Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | skipping header 582482
20190626T050722.778243Z |     INFO | interface.[e-1.claudioboxx.com:50002] | disconnecting due to: TimeoutError(10060, "Connect call failed ('37.61.209.146', 50002)")
20190626T050722.778243Z |     INFO | network | couldn't launch iface e-1.claudioboxx.com:50002:s -- CancelledError()
20190626T050723.442116Z |     INFO | interface.[e10.keff.org:50002] | skipping header 582482
20190626T050725.202831Z |     INFO | interface.[thanos.xskyx.net:50002] | skipping header 582482
20190626T050725.854527Z |     INFO | interface.[77.20.219.157:50001] | skipping header 582482
20190626T050727.322672Z |     INFO | interface.[electrum3.hodlister.co:50002] | skipping header 582482
20190626T050727.735126Z |     INFO | interface.[electrum.lightning.supplies:50002] | skipping header 582482
20190626T050733.143260Z |     INFO | network | network: retrying connections
20190626T050734.170712Z |     INFO | network | fee_histogram [[112, 100694], [96, 116802], [92, 173613], [90, 181644], [82, 39804], [15, 161664], [6, 1507868], [5, 879228], [4, 649553], [3, 992046], [2, 1137129], [1, 3407287]]
20190626T050734.171680Z |     INFO | network | fee_estimates {25: 37915, 10: 86991, 5: 91631, 2: 91631}
20190626T050740.129089Z |     INFO | interface.[electrum.mindspot.org:50002] | disconnecting due to: TimeoutError(10060, "Connect call failed ('172.103.153.90', 50002)")
20190626T050740.132087Z |     INFO | network | couldn't launch iface electrum.mindspot.org:50002:s -- CancelledError()
20190626T050741.341276Z |     INFO | interface.[electrumx.ml:50002] | skipping header 582482
20190626T050744.215292Z |     INFO | interface.[fn.48.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('5.79.90.70', 50002)"),)
20190626T050744.218300Z |     INFO | network | couldn't launch iface fn.48.org:50002:s -- CancelledError()
20190626T050745.707747Z |     INFO | interface.[e2.keff.org:50002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 194.71.0.0/16',)
20190626T050745.708746Z |     INFO | network | couldn't launch iface e2.keff.org:50002:s -- CancelledError()
20190626T050747.221153Z |     INFO | interface.[btc.litepay.ch:50002] | succeeded in getting cert
20190626T050748.063890Z |     INFO | interface.[btc.litepay.ch:50002] | connection established. version: ['ElectrumX 1.11.0', '1.4']
20190626T050748.234685Z |     INFO | interface.[btc.litepay.ch:50002] | set blockchain with height 582482
20190626T050748.235682Z |     INFO | interface.[btc.litepay.ch:50002] | skipping header 582482
20190626T050801.435986Z |     INFO | interface.[tomscryptos.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2a01:4f9:2a:1c8a::2', 50002, 0, 0), [Errno 10060] Connect call failed ('95.216.28.117', 50002)",),)
20190626T050801.435986Z |     INFO | network | couldn't launch iface tomscryptos.com:50002:s -- CancelledError()
20190626T050801.990827Z |     INFO | interface.[electrumx.ftp.sh:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190626T050801.993814Z |     INFO | network | couldn't launch iface electrumx.ftp.sh:50002:s -- CancelledError()
20190626T050804.377651Z |     INFO | interface.[electrum-server.ninja:50002] | disconnecting due to: SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)')
20190626T050804.379646Z |     INFO | network | couldn't launch iface electrum-server.ninja:50002:s -- CancelledError()
20190626T050805.718385Z |     INFO | interface.[electrum.emzy.de:50002] | connection established. version: ['ElectrumX 1.12', '1.4']
20190626T050805.899731Z |     INFO | interface.[electrum.emzy.de:50002] | set blockchain with height 582482
20190626T050805.901726Z |     INFO | interface.[electrum.emzy.de:50002] | skipping header 582482
20190626T050833.174304Z |     INFO | network | network: retrying connections
20190626T050834.204564Z |     INFO | network | fee_histogram [[91, 114117], [6, 1416668], [5, 878842], [4, 649553], [3, 991820], [2, 1136514], [1, 3400017]]
20190626T050834.205561Z |     INFO | network | fee_estimates {25: 37915, 10: 86991, 5: 91631, 2: 91631}
20190626T050904.303673Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T050905.120983Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T050933.254236Z |     INFO | network | network: retrying connections
20190626T050934.282123Z |     INFO | network | fee_histogram [[91, 114117], [6, 1416668], [5, 878842], [4, 649553], [3, 991820], [2, 1136514], [1, 3400017]]
20190626T050934.283121Z |     INFO | network | fee_estimates {25: 37915, 10: 86991, 5: 91631, 2: 91631}
20190626T051033.304794Z |     INFO | network | network: retrying connections
20190626T051034.338634Z |     INFO | network | fee_histogram [[150, 105584], [92, 162458], [90, 106259], [60, 92640], [6, 1474405], [5, 882044], [4, 649553], [3, 992071], [2, 1136514], [1, 3400273]]
20190626T051034.339624Z |     INFO | network | fee_estimates {25: 37915, 10: 86991, 5: 91631, 2: 91631}
20190626T051133.350161Z |     INFO | network | network: retrying connections
20190626T051134.380934Z |     INFO | network | fee_histogram [[150, 105584], [92, 162458], [90, 106259], [60, 92640], [6, 1474405], [5, 882044], [4, 649553], [3, 992071], [2, 1136514], [1, 3400273]]
20190626T051134.380934Z |     INFO | network | fee_estimates {25: 37915, 10: 86991, 5: 91631, 2: 91631}
20190626T051135.113514Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T051135.907589Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T051153.218131Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | could connect 582483
20190626T051153.479853Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20190626T051153.483843Z |     INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
20190626T051153.483843Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0030
20190626T051153.484840Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0050
20190626T051154.592691Z |     INFO | interface.[e10.keff.org:50002] | skipping header 582483
20190626T051155.401066Z |     INFO | interface.[thanos.xskyx.net:50002] | skipping header 582483
20190626T051156.334374Z |     INFO | interface.[electrum.lightning.supplies:50002] | skipping header 582483
20190626T051156.747795Z |     INFO | interface.[btc.litepay.ch:50002] | skipping header 582483
20190626T051157.219427Z |     INFO | interface.[electrum.emzy.de:50002] | skipping header 582483
20190626T051157.442290Z |     INFO | interface.[electrum3.hodlister.co:50002] | skipping header 582483
20190626T051158.623440Z |     INFO | interface.[electrum.nute.net:17315] | skipping header 582483
20190626T051200.397614Z |     INFO | interface.[77.20.219.157:50001] | skipping header 582483
20190626T051214.511568Z |     INFO | interface.[electrumx.ml:50002] | skipping header 582483
20190626T051233.449080Z |     INFO | network | network: retrying connections
20190626T051234.476684Z |     INFO | network | fee_histogram [[90, 108887], [6, 1148956], [5, 876460], [4, 649031], [3, 992382], [2, 1133042], [1, 3430229]]
20190626T051234.476684Z |     INFO | network | fee_estimates {25: 37916, 10: 86992, 5: 91627, 2: 91627}
20190626T051242.981849Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | could connect 582484
20190626T051243.279289Z |     INFO | interface.[btc.litepay.ch:50002] | skipping header 582484
20190626T051243.481389Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20190626T051243.485348Z |     INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
20190626T051243.485348Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0030
20190626T051243.486345Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0050
20190626T051245.675595Z |     INFO | interface.[electrum.nute.net:17315] | skipping header 582484
20190626T051248.228097Z |     INFO | interface.[electrum.lightning.supplies:50002] | skipping header 582484
20190626T051249.007826Z |     INFO | interface.[electrum.emzy.de:50002] | skipping header 582484
20190626T051249.600078Z |     INFO | interface.[electrum3.hodlister.co:50002] | skipping header 582484
20190626T051252.745836Z |     INFO | interface.[thanos.xskyx.net:50002] | skipping header 582484
20190626T051255.099555Z |     INFO | interface.[77.20.219.157:50001] | skipping header 582484
20190626T051255.484505Z |     INFO | interface.[e10.keff.org:50002] | skipping header 582484
20190626T051333.479811Z |     INFO | network | network: retrying connections
20190626T051334.499826Z |     INFO | network | fee_histogram [[90, 108887], [6, 1148956], [5, 876460], [4, 649031], [3, 992382], [2, 1133042], [1, 3430229]]
20190626T051334.499826Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T051335.313422Z |     INFO | interface.[electrumx.ml:50002] | skipping header 582484
20190626T051405.913301Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T051406.707258Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T051412.437794Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T051413.219036Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T051433.551654Z |     INFO | network | network: retrying connections
20190626T051434.585537Z |     INFO | network | fee_histogram [[93, 114196], [90, 119485], [9, 112033], [6, 175407], [5, 885711], [4, 649461], [3, 992914], [2, 1133253], [1, 3431142]]
20190626T051434.586535Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T051533.553750Z |     INFO | network | network: retrying connections
20190626T051534.692018Z |     INFO | network | fee_histogram [[93, 114196], [90, 119485], [9, 112033], [6, 175407], [5, 885711], [4, 649461], [3, 992914], [2, 1133253], [1, 3431142]]
20190626T051534.692018Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T051633.653819Z |     INFO | network | network: retrying connections
20190626T051634.760677Z |     INFO | network | fee_histogram [[101, 104013], [92, 147918], [90, 136281], [62, 83861], [7, 186161], [6, 133023], [5, 899663], [4, 652093], [3, 993139], [2, 1134177], [1, 3437887]]
20190626T051634.760677Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T051643.207962Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T051643.982789Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T051733.706618Z |     INFO | network | network: retrying connections
20190626T051734.821141Z |     INFO | network | fee_histogram [[101, 104013], [92, 147918], [90, 136281], [62, 83861], [7, 186161], [6, 133023], [5, 899663], [4, 652093], [3, 993139], [2, 1134177], [1, 3437887]]
20190626T051734.822145Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T051833.768458Z |     INFO | network | network: retrying connections
20190626T051834.914209Z |     INFO | network | fee_histogram [[106, 100926], [95, 123528], [92, 129536], [90, 171519], [62, 105615], [9, 167029], [6, 243051], [5, 902355], [4, 652093], [3, 993139], [2, 1134177], [1, 3438048]]
20190626T051834.914209Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T051913.978204Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T051914.860712Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T051933.792871Z |     INFO | network | network: retrying connections
20190626T051934.924856Z |     INFO | network | fee_histogram [[106, 100926], [95, 123528], [92, 129536], [90, 171519], [62, 105615], [9, 167029], [6, 243051], [5, 902355], [4, 652093], [3, 993139], [2, 1134177], [1, 3438048]]
20190626T051934.924856Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T052033.814476Z |     INFO | network | network: retrying connections
20190626T052034.931212Z |     INFO | network | fee_histogram [[106, 100926], [95, 123528], [92, 129536], [90, 171519], [62, 105615], [9, 167029], [6, 243051], [5, 902355], [4, 652093], [3, 993139], [2, 1134177], [1, 3438048]]
20190626T052034.931212Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T052133.906224Z |     INFO | network | network: retrying connections
20190626T052134.929487Z |     INFO | network | fee_histogram [[120, 100049], [96, 126247], [93, 114784], [91, 156161], [90, 138717], [62, 144008], [16, 176898], [7, 203623], [5, 1073107], [4, 652093], [3, 993298], [2, 1140198], [1, 3438271]]
20190626T052134.929487Z |     INFO | network | fee_estimates {25: 37914, 10: 86992, 5: 91626, 2: 91626}
20190626T052144.864912Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T052139.634392Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T052223.413288Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | could connect 582485
20190626T052223.428248Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20190626T052223.429245Z |     INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
20190626T052223.429245Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0010
20190626T052223.429245Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0010
20190626T052223.772328Z |     INFO | interface.[e10.keff.org:50002] | skipping header 582485
20190626T052224.407629Z |     INFO | interface.[electrum3.hodlister.co:50002] | skipping header 582485
20190626T052224.473453Z |     INFO | interface.[electrum.emzy.de:50002] | skipping header 582485
20190626T052224.861414Z |     INFO | interface.[electrum.nute.net:17315] | skipping header 582485
20190626T052227.413587Z |     INFO | interface.[electrum.lightning.supplies:50002] | skipping header 582485
20190626T052227.894303Z |     INFO | interface.[thanos.xskyx.net:50002] | skipping header 582485
20190626T052228.482727Z |     INFO | interface.[btc.litepay.ch:50002] | skipping header 582485
20190626T052230.427526Z |     INFO | interface.[77.20.219.157:50001] | skipping header 582485
20190626T052233.955090Z |     INFO | network | network: retrying connections
20190626T052234.986331Z |     INFO | network | fee_histogram [[120, 100049], [96, 126247], [93, 114784], [91, 156161], [90, 138717], [62, 144008], [16, 176898], [7, 203623], [5, 1073107], [4, 652093], [3, 993298], [2, 1140198], [1, 3438271]]
20190626T052234.986331Z |     INFO | network | fee_estimates {25: 37914, 10: 86995, 5: 91456, 2: 91628}
20190626T052238.046175Z |     INFO | interface.[electrumx.ml:50002] | skipping header 582485
20190626T052333.962504Z |     INFO | network | network: retrying connections
20190626T052335.080240Z |     INFO | network | fee_histogram [[50, 104067], [16, 121614], [8, 124705], [6, 267960], [5, 927954], [4, 651947], [3, 993298], [2, 1140570], [1, 3438541]]
20190626T052335.081238Z |     INFO | network | fee_estimates {25: 37914, 10: 86995, 5: 91456, 2: 91628}
20190626T052409.641948Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T052410.754497Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T052433.980488Z |     INFO | network | network: retrying connections
20190626T052435.114590Z |     INFO | network | fee_histogram [[50, 104067], [16, 121614], [8, 124705], [6, 267960], [5, 927954], [4, 651947], [3, 993298], [2, 1140570], [1, 3438541]]
20190626T052435.115589Z |     INFO | network | fee_estimates {25: 37914, 10: 86995, 5: 91456, 2: 91628}
20190626T052533.983798Z |     INFO | network | network: retrying connections
20190626T052535.114436Z |     INFO | network | fee_histogram [[150, 111176], [92, 120573], [63, 102874], [19, 130174], [8, 184578], [6, 294861], [5, 941080], [4, 651947], [3, 993521], [2, 1140570], [1, 3438893]]
20190626T052535.114436Z |     INFO | network | fee_estimates {25: 37914, 10: 86995, 5: 91456, 2: 91628}
20190626T052634.039201Z |     INFO | network | network: retrying connections
20190626T052635.185170Z |     INFO | network | fee_histogram [[150, 111176], [92, 120573], [63, 102874], [19, 130174], [8, 184578], [6, 294861], [5, 941080], [4, 651947], [3, 993521], [2, 1140570], [1, 3438893]]
20190626T052635.185170Z |     INFO | network | fee_estimates {25: 37914, 10: 86995, 5: 91456, 2: 91628}
20190626T052640.765861Z |     INFO | exchange_rate.BitcoinAverage | getting fx quotes for USD
20190626T052641.724709Z |     INFO | exchange_rate.BitcoinAverage | received fx quotes
20190626T052707.647394Z |     INFO | gui.qt.main_window.[default_wallet] | close_wallet c:\users\will\appdata\roaming\electrum\wallets\default_wallet
20190626T052707.692707Z |     INFO | storage.WalletStorage | saved c:\users\will\appdata\roaming\electrum\wallets\default_wallet
20190626T052707.693705Z |    DEBUG | util.profiler | WalletStorage.write 0.0434
20190626T052707.714366Z |     INFO | daemon.Daemon | shutting down network
20190626T052707.714366Z |     INFO | network | stopping network
20190626T052707.779804Z |     INFO | interface.[electrum.lightning.supplies:50002] | disconnecting due to: CancelledError()
20190626T052707.791896Z |     INFO | plugin.Plugins | stopped
20190626T052707.883116Z |     INFO | interface.[btc.litepay.ch:50002] | disconnecting due to: CancelledError()
20190626T052707.900584Z |     INFO | interface.[electrum.emzy.de:50002] | disconnecting due to: CancelledError()
20190626T052707.904579Z |     INFO | interface.[thanos.xskyx.net:50002] | disconnecting due to: CancelledError()
20190626T052707.909884Z |     INFO | interface.[electrum3.hodlister.co:50002] | disconnecting due to: CancelledError()
20190626T052707.919618Z |     INFO | interface.[electrum824420.fullhealth.net:50022] | disconnecting due to: CancelledError()
20190626T052707.920615Z |     INFO | interface.[electrum.nute.net:17315] | disconnecting due to: CancelledError()
20190626T052707.944014Z |     INFO | interface.[e10.keff.org:50002] | disconnecting due to: CancelledError()
20190626T052707.948927Z |     INFO | interface.[77.20.219.157:50001] | disconnecting due to: CancelledError()
20190626T052709.714690Z |     INFO | network | exc during main_taskgroup cancellation: TimeoutError()
20190626T052709.716018Z |     INFO | daemon.Daemon | stopped

**Comment by SomberNight** [comment]
Thanks, yes, this is what I meant.
Indeed it seems the history got corrupted somehow:
```
20190623T075927.540604Z | INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
20190623T075927.863741Z | INFO | wallet.Standard_Wallet.[default_wallet] | Error: history not synchronized
```
Not sure yet how.

> Restoring did nothing. Still no history. It was there one second, and as soon as I increased the fee, it went blank.

Are you sure you correctly opened the new wallet after restoring from seed?
Restoring should fix it.

**Comment by VNBM** [comment]
Yes I am. The balance, and all my addresses as well as saved address book all still show. I can also see the transaction for increasing the fee under the “coins” tab. But the history is still blank.

**Comment by SomberNight** [comment]
Run `wallet.clear_history()` in the `Console` tab and then restart the application

**Comment by VNBM** [comment]
When this was done previously, it didn’t do anything. For some reason, it did this time, history is all showing correctly now.

Thank you very much for your assistance!
