### ISSUE TITLE
Use Fault objects to set JSON-RPC error codes

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5524]
Currently, Electrum's JSON-RPC methods in `commands.py` raise Exceptions when they encounter an error condition.  Unfortunately, `jsonrpclib` hardcodes a JSON-RPC error code of `-32603` when an RPC method raises an Exception.  This makes it impossible for JSON-RPC client applications to disambiguate what error occurred, unless they want to scrape the plaintext description of the error (bad idea).

`jsonrpclib`'s canonical pattern for setting a JSON-RPC error code is to return a `Fault` object instead of raising an Exception.  For example, in Electrum-NMC's master branch, I currently have this code in the `name_show` method when a nonexistent name is requested:

~~~
raise NameNotFoundError("Name never existed, is expired, or is unconfirmed")
~~~

Which unfortunately results in the hardcoded error code of `-32603`.  Changing that line to this:

~~~
from jsonrpclib import Fault
return Fault(-4, "Name never existed, is expired, or is unconfirmed")
~~~

Results in the desired error code of `-4` (which happens to match the error code that Namecoin Core gives for that case, so JSON-RPC clients don't need to do things differently for Namecoin Core and Electrum-NMC).

Unfortunately, as @SomberNight pointed out on IRC, using `Fault` objects in the method implementations means we're contaminating the Electrum codebase with an implementation quirk of the `jsonrpclib` library.  It sounds like it would be preferable to instead continue to raise Exceptions in the methods (potentially a custom type), which would be caught by the `command` decorator and converted to a `Fault` here: https://github.com/spesmilo/electrum/blob/f60f690ca944b9611a6cbf7b29a8a8aab5f13b21/electrum/commands.py#L96 .

@SomberNight also points out that this change would need to be tested via both JSON-RPC and the plain CLI interface, since both of those interfaces call these methods.

AFAICT if a raised Exception isn't from a custom type that can be readily converted to a `Fault`, we can just not catch it, and `jsonrpclib` will automatically convert it to a `Fault` with the default error code of `-32603`.  For reference, the plaintext description that `jsonrpclib` produces and sends over the JSON-RPC wire for the above Electrum-NMC example (when an Exception is raised by the method) looks something like this:

~~~
Server error: File "/home/user/Downloads/Electrum-NMC-3.3.6/electrum_nmc/commands.py", line 1029, in name_show | electrum_nmc.commands.NameNotFoundError: Name never existed, is expired, or is unconfirmed
~~~

Which is about as good as we can get without having an explicit error code to give.

I don't have time to work on this issue in the immediate future.  I might pick it up later, but if anyone else would like to try their hand at it, by all means feel free.

**Comment by ecdsa** [comment]
please note that we will no longer use jsonrpclib once lightning is merged.
see 5df5aaa96d35acb854cb7e7098e5ef23e85c751e

**Comment by ecdsa** [comment]
this should be fixed now. let me know

**Comment by SomberNight** [comment]
Right, you are correct in that we still don't return meaningful error codes.
The original issue is somewhat conflating fixing this with using `jsonrpclib.Fault` which is no longer applicable as we stopped using that dependency - I guess this is what @ecdsa meant.

Sounds like you might want to be able to define certain error scenarios which have their own corresponding error codes.
I guess the easiest way to do this would be to raise a custom subclass of Exception which has a code field set and handle that in daemon.py around the line you pointed to.
