### ISSUE TITLE
[Lightning] Electrum crashes when LN request doesn't include amount

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#5761]
When copying a payment request from here https://tippin.me/@lukechilds with no amount and manually entering an amount in the UI the application instantly exits when I click send.

This is dumped to the terminal:

```
E | lnworker.LNWallet | Exception in _pay: TypeError("unsupported operand type(s) for *: 'NoneType' and 'int'")                                                                                                                       [10/221]
Traceback (most recent call last):
  File "/Users/lukechilds/dev/oss/electrum/electrum/util.py", line 988, in wrapper
    return await func(*args, **kwargs)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 849, in _pay
    route = await self._create_route_from_invoice(decoded_invoice=lnaddr)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 954, in _create_route_from_invoice
    amount_msat = int(decoded_invoice.amount * COIN * 1000)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
QObject::setParent: Cannot set parent, new parent is in a different thread
2019-11-16 22:54:01.154 Python[8600:5456190] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff3c54143d __exceptionPreprocess + 256
        1   libobjc.A.dylib                     0x00007fff6844f720 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff3c55aec1 -[NSException raise] + 9
        3   AppKit                              0x00007fff39a5f2a5 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
        4   AppKit                              0x00007fff39a5c68c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
        5   AppKit                              0x00007fff39b1cedf -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
        6   AppKit                              0x00007fff39a5c0b6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
        7   AppKit                              0x00007fff39b1ce94 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
        8   AppKit                              0x00007fff39d2f20c -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 52
        9   libqcocoa.dylib                     0x0000000108a15475 qt_plugin_instance + 164165
        10  libqcocoa.dylib                     0x0000000108a01f6b qt_plugin_instance + 85051
        11  libqcocoa.dylib                     0x00000001089fbd46 qt_plugin_instance + 59926
        12  libqcocoa.dylib                     0x00000001089fb81d qt_plugin_instance + 58605
        13  QtGui                               0x000000010414eb66 _ZN14QWindowPrivate6createEby + 134
        14  QtWidgets                           0x00000001055a5971 _ZN14QWidgetPrivate6createEv + 1201
        15  QtWidgets                           0x00000001055a4686 _ZN7QWidget6createEybb + 326
        16  QtWidgets                           0x00000001055b732d _ZN14QWidgetPrivate10setVisibleEb + 189
        17  QtWidgets                           0x0000000105778252 _ZN7QDialog10setVisibleEb + 258
        18  QtWidgets.so                        0x000000010517c0bc _ZN14sipQMessageBox10setVisibleEb + 108
        19  QtWidgets                           0x0000000105777ab3 _ZN7QDialog4execEv + 243
        20  QtWidgets.so                        0x0000000105091bdb _ZL18meth_QDialog_exec_P7_objectS0_ + 171
        21  Python                              0x00000001010b43af _PyMethodDef_RawFastCallKeywords + 235
        22  Python                              0x00000001010b3a38 _PyCFunction_FastCallKeywords + 41
        23  Python                              0x0000000101148368 call_function + 628
        24  Python                              0x0000000101141343 _PyEval_EvalFrameDefault + 6767
        25  Python                              0x0000000101148bc9 _PyEval_EvalCodeWithName + 1698
        26  Python                              0x00000001010b3a00 _PyFunction_FastCallKeywords + 212
        27  Python                              0x00000001011483d5 call_function + 737
        28  Python                              0x0000000101141486 _PyEval_EvalFrameDefault + 7090
        29  Python                              0x0000000101148bc9 _PyEval_EvalCodeWithName + 1698
        30  Python                              0x00000001010b3678 _PyFunction_FastCallDict + 444
        31  Python                              0x00000001010b477f _PyObject_Call_Prepend + 131
        32  Python                              0x00000001010b3b45 PyObject_Call + 136
        33  Python                              0x0000000101141627 _PyEval_EvalFrameDefault + 7507
        34  Python                              0x0000000101148bc9 _PyEval_EvalCodeWithName + 1698
        35  Python                              0x00000001010b3a00 _PyFunction_FastCallKeywords + 212
        36  Python                              0x00000001011483d5 call_function + 737
        37  Python                              0x0000000101141343 _PyEval_EvalFrameDefault + 6767
        38  Python                              0x0000000101148bc9 _PyEval_EvalCodeWithName + 1698
        39  Python                              0x00000001010b3a00 _PyFunction_FastCallKeywords + 212
        40  Python                              0x00000001011483d5 call_function + 737
        41  Python                              0x0000000101141343 _PyEval_EvalFrameDefault + 6767
        42  Python                              0x00000001010b3e0c function_code_fastcall + 106
        43  Python                              0x00000001010b477f _PyObject_Call_Prepend + 131
        44  Python                              0x00000001010b3b45 PyObject_Call + 136
        45  sip.so                              0x0000000104c96f68 call_method + 76
        46  sip.so                              0x0000000104c92cf8 sip_api_call_procedure_method + 152
        47  QtCore.so                           0x0000000104d846d4 _ZN10sipQThread3runEv + 84
        48  QtCore                              0x000000010468c6e3 _ZN7QThread11qt_metacallEN11QMetaObject4CallEiPPv + 1155
        49  libsystem_pthread.dylib             0x00007fff6970f33d _pthread_body + 126
        50  libsystem_pthread.dylib             0x00007fff697122a7 _pthread_start + 70
        51  libsystem_pthread.dylib             0x00007fff6970e425 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      ./run_electrum
```

When using a payment request with an amount specified like https://tippin.me/@lukechilds/10000 the application doesn't crash.

**Comment by lukechilds** [comment]
Sorry, I've just realised I'm 5 days behind master, let me pull and test this again. (Same goes for https://github.com/spesmilo/electrum/issues/5762)

**Comment by lukechilds** [comment]
Can confirm this is still an issue as of current tip of master: cbd146ad1501841a05f66135e203cccb3565141d

Updated terminal dump:

```
E | lnworker.LNWallet | Exception in _pay: InvoiceError('Missing amount')                                                                                                                                                              [3/514]
Traceback (most recent call last):
  File "/Users/lukechilds/dev/oss/electrum/electrum/util.py", line 988, in wrapper
    return await func(*args, **kwargs)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 859, in _pay
    self._check_invoice(invoice, amount_sat)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 961, in _check_invoice
    raise InvoiceError(_("Missing amount"))
electrum.util.InvoiceError: Missing amount
QObject::setParent: Cannot set parent, new parent is in a different thread
2019-11-17 12:45:20.773 Python[11932:5626289] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff3c54143d __exceptionPreprocess + 256
        1   libobjc.A.dylib                     0x00007fff6844f720 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff3c55aec1 -[NSException raise] + 9
        3   AppKit                              0x00007fff39a5f2a5 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
        4   AppKit                              0x00007fff39a5c68c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
        5   AppKit                              0x00007fff39b1cedf -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
        6   AppKit                              0x00007fff39a5c0b6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
        7   AppKit                              0x00007fff39b1ce94 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
        8   AppKit                              0x00007fff39d2f20c -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 52
        9   libqcocoa.dylib                     0x000000010d4b9475 qt_plugin_instance + 164165
        10  libqcocoa.dylib                     0x000000010d4a5f6b qt_plugin_instance + 85051
        11  libqcocoa.dylib                     0x000000010d49fd46 qt_plugin_instance + 59926
        12  libqcocoa.dylib                     0x000000010d49f81d qt_plugin_instance + 58605
        13  QtGui                               0x000000010b6a1b66 _ZN14QWindowPrivate6createEby + 134
        14  QtWidgets                           0x000000010cb9a971 _ZN14QWidgetPrivate6createEv + 1201
        15  QtWidgets                           0x000000010cb99686 _ZN7QWidget6createEybb + 326
        16  QtWidgets                           0x000000010cbac32d _ZN14QWidgetPrivate10setVisibleEb + 189
        17  QtWidgets                           0x000000010cd6d252 _ZN7QDialog10setVisibleEb + 258
        18  QtWidgets.so                        0x000000010c7710bc _ZN14sipQMessageBox10setVisibleEb + 108
        19  QtWidgets                           0x000000010cd6cab3 _ZN7QDialog4execEv + 243
        20  QtWidgets.so                        0x000000010c686bdb _ZL18meth_QDialog_exec_P7_objectS0_ + 171
        21  Python                              0x00000001084223af _PyMethodDef_RawFastCallKeywords + 235
        22  Python                              0x0000000108421a38 _PyCFunction_FastCallKeywords + 41
        23  Python                              0x00000001084b6368 call_function + 628
        24  Python                              0x00000001084af343 _PyEval_EvalFrameDefault + 6767
        25  Python                              0x00000001084b6bc9 _PyEval_EvalCodeWithName + 1698
        26  Python                              0x0000000108421a00 _PyFunction_FastCallKeywords + 212
        27  Python                              0x00000001084b63d5 call_function + 737
        28  Python                              0x00000001084af486 _PyEval_EvalFrameDefault + 7090
        29  Python                              0x00000001084b6bc9 _PyEval_EvalCodeWithName + 1698
        30  Python                              0x0000000108421678 _PyFunction_FastCallDict + 444
        31  Python                              0x000000010842277f _PyObject_Call_Prepend + 131
        32  Python                              0x0000000108421b45 PyObject_Call + 136
        33  Python                              0x00000001084af627 _PyEval_EvalFrameDefault + 7507
        34  Python                              0x00000001084b6bc9 _PyEval_EvalCodeWithName + 1698
        35  Python                              0x0000000108421a00 _PyFunction_FastCallKeywords + 212
        36  Python                              0x00000001084b63d5 call_function + 737
        37  Python                              0x00000001084af343 _PyEval_EvalFrameDefault + 6767
        38  Python                              0x00000001084b6bc9 _PyEval_EvalCodeWithName + 1698
        39  Python                              0x0000000108421a00 _PyFunction_FastCallKeywords + 212
        40  Python                              0x00000001084b63d5 call_function + 737
        41  Python                              0x00000001084af343 _PyEval_EvalFrameDefault + 6767
        42  Python                              0x0000000108421e0c function_code_fastcall + 106
        43  Python                              0x000000010842277f _PyObject_Call_Prepend + 131
        44  Python                              0x0000000108421b45 PyObject_Call + 136
        45  sip.so                              0x000000010b1aff68 call_method + 76
        46  sip.so                              0x000000010b1abcf8 sip_api_call_procedure_method + 152
        47  QtCore.so                           0x000000010c2796d4 _ZN10sipQThread3runEv + 84
        48  QtCore                              0x000000010bbdf6e3 _ZN7QThread11qt_metacallEN11QMetaObject4CallEiPPv + 1155
        49  libsystem_pthread.dylib             0x00007fff6970f33d _pthread_body + 126
        50  libsystem_pthread.dylib             0x00007fff697122a7 _pthread_start + 70
        51  libsystem_pthread.dylib             0x00007fff6970e425 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      ./run_electrum
```

**Comment by ecdsa** [comment]
the crash should be fixed in 47e0b4c
the error message needs to be improved

**Comment by lukechilds** [comment]
Can confirm I now get a helpful error as of ade47e331a6c5ab9c386eedce1f67b766ecb4ec3

<img width="1226" alt="Screenshot 2019-11-18 at 11 32 35" src="https://user-images.githubusercontent.com/2123375/69024876-4f495700-09f7-11ea-8b0e-6c79d14eefe6.png">

I'm assuming support for invoices without amounts and then manually entering an amount in the UI is planned but just not yet implemented. Is that correct?

**Comment by ecdsa** [comment]
done now

**Comment by lukechilds** [comment]
@ecdsa still doesn't seem to be working for me:

<img width="1226" alt="Screenshot 2019-11-18 at 12 05 33" src="https://user-images.githubusercontent.com/2123375/69026021-d26cac00-09fb-11ea-8fc5-e2cbdb42d603.png">

Using invoice:

```
lnbc1pwayf54pp50sys28x7n0m9v8d5ym0g8v5ee0wa5v5rk085hx2n6p782u9h0g9qdpu235hqurfdcsxcattv43ks6tvv3ejq2r5d9c8q6tw9ekk22fgw5cnydpsxv5scqzpgxqyz5vqty3y3urutgw9md34fpvdsnd2nt3tye6ltllvz4vvcdnag74haswnguszpdxpjy0hh2addqa7s74qxz2tqyl5lejkj7tsq6r9tttgs0gq396f9u
```

Generated from: https://tippin.me/@lukechilds

I added a $1 (11784) amount in the GUI but still got the error.

```
E | lnworker.LNWallet | Exception in _pay: InvoiceError('Missing amount')
Traceback (most recent call last):
  File "/Users/lukechilds/dev/oss/electrum/electrum/util.py", line 988, in wrapper
    return await func(*args, **kwargs)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 859, in _pay
    self._check_invoice(invoice, amount_sat)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 961, in _check_invoice
    raise InvoiceError(_("Missing amount"))
electrum.util.InvoiceError: Missing amount
E | gui.qt.main_window.[Luke Vanity Address] | on_error
Traceback (most recent call last):
  File "/Users/lukechilds/dev/oss/electrum/electrum/gui/qt/util.py", line 730, in run
    result = task.task()
  File "/Users/lukechilds/dev/oss/electrum/electrum/gui/qt/main_window.py", line 1397, in task
    self.wallet.lnworker.pay(invoice, amount_sat, attempts)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 838, in pay
    success = fut.result()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/lukechilds/dev/oss/electrum/electrum/util.py", line 988, in wrapper
    return await func(*args, **kwargs)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 859, in _pay
    self._check_invoice(invoice, amount_sat)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 961, in _check_invoice
    raise InvoiceError(_("Missing amount"))
electrum.util.InvoiceError: Missing amount
```

On b9cf095e1a0e44121fd4f3b1861c14ff82d36931

**Comment by lukechilds** [comment]
You can see it now shows the correct amount in the "Outgoing payments" list instead of "unknown", but trying to pay the actual invoice still gives the `InvoiceError('Missing amount')` error.

**Comment by ecdsa** [comment]
should work now.

**Comment by lukechilds** [comment]
Yep, aa37979100b9119414026862444bfdb13295e6d3 is working for me! 🎉
