### ISSUE TITLE
Receive tab should not offer addresses with previous transactions

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#5864]
I have a wallet where the first address has 8 transactions but 0 balance. The receive tab is offering that first address for some reason, which seems like a bug to me. This is on version 3.3.8 on windows.

**Comment by SomberNight** [comment]
Is this right after you have restored from seed/xpub?

This is a know bug, the receive address does not get updated automatically; you need to press the "New" button.
See https://github.com/spesmilo/electrum/issues/3812

This is already fixed on master.

**Comment by fresheneesz** [comment]
> This is already fixed on master.

Wit, but that bug was closed 7 months ago. Are you saying that the bug has been fixed for 7 months but still isn't in a released version?

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/issues/3812 was closed with https://github.com/spesmilo/electrum/commit/41802d8094f07398254ed49093ce312a56f29cce
That commit is in 3.3.7 and 3.3.8.
If the receive tab address is used, it is coloured red, and there is a privacy warning in the tooltip.
It turns out that this colouring does not work on MacOS however ( https://github.com/spesmilo/electrum/issues/5374#issuecomment-508576708 ), due to a bug in Qt.

**Comment by fresheneesz** [comment]
> Is this right after you have restored from seed/xpub?

This is after creating a new electrum wallet using an existing hardware wallet. 

> That commit is in 3.3.7 and 3.3.8.

If the commit is in the version I'm using (v3.3.8) and I'm still seeing a problem, I think this issue should be reopened. 

> If the receive tab address is used, it is coloured red, and there is a privacy warning in the tooltip.

I do see it colored red for me (and I do see the privacy tooltip if I hover). The question is, why is this address being offered at all?
