### ISSUE TITLE
client trusts server for fee estimates. lightning channel might get force-closed if fees are vastly different than what remote expects

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6027]
We (Electrum client) currently trust the main connected Electrum server for fee estimates.
(The feerates are clamped between 1 sat/byte and 1500 sat/byte, as a safeguard.)

This is ~okay for typical on-chain txs but presents an issue for lightning.

From [BOLT-02](https://github.com/lightningnetwork/lightning-rfc/blob/85068c509979d225eb54d726315deb8d780ac42a/02-peer-protocol.md#updating-fees-update_fee):

> `update_fee` message
> A receiving node:
>    - if the `update_fee` is too low for timely processing, OR is unreasonably large:
>        - SHOULD fail the channel.

Note that only the funder of a channel can send `update_fee`.

So, two cases to consider.
- If the remote is the funder, when we receive `update_fee` we "should" force-close if the the suggested fee is unreasonable. (Similarly if we don't receive `update_fee` for some time, the fee on the latest ctx should be checked to be reasonable)
    - The problem here is that we would be checking the suggested feerate against what the Electrum server tells us.
- If we are the funder, we should send `update_fee` to keep the feerate of the latest ctx at a reasonable level.
    - However, the Electrum server can trigger us to send an `update_fee`, by giving us new fee estimates, and further we just blindly trust the Electrum server for these estimates.

So, e.g. if we are the funder of a channel, the Electrum server could send us unreasonable fee estimates, we would send `update_fee` to the channel counterparty, and the remote might then could plausibly force-close the channel.

-----

Do other lightning implementations actually force-close when receiving an unreasonable `update_fee`?

AFAICT:
- no, `lnd` does NOT force-close
    <details>
     <summary>source</summary>
    
    https://github.com/lightningnetwork/lnd/blob/5d5069c47703275b76d9ee83bef9fdd325827f99/htlcswitch/link.go#L1934
    https://github.com/lightningnetwork/lnd/blob/38b521d87d3fd9cff628e5dc09b764aeabaf011a/lnwallet/channel.go#L6252
    https://github.com/lightningnetwork/lnd/blob/38b521d87d3fd9cff628e5dc09b764aeabaf011a/lnwallet/channel.go#L6214
</details>

- yes, `clightning` does force-close:
    I think they force-close if the feerate is outside the range:
    `[FEERATE_SLOW / 2, FEERATE_URGENT * 10]`,
    where `FEERATE_SLOW = "bitcoind 100-block ECONOMICAL estimate"`, and `FEERATE_URGENT = "bitcoind 2-block CONSERVATIVE estimate"`
    <details>
     <summary>source</summary>
    
    https://github.com/ElementsProject/lightning/blob/faac4b28adee5221e83787d64cd5d30b16b62097/channeld/channeld.c#L1679
    https://github.com/ElementsProject/lightning/blob/faac4b28adee5221e83787d64cd5d30b16b62097/channeld/channeld.c#L668
    https://github.com/ElementsProject/lightning/blob/a47fd8cf3e1c04fb4f3a6b7a7d0c5d8160c2cd69/lightningd/chaintopology.c#L815
    https://github.com/ElementsProject/lightning/blob/a47fd8cf3e1c04fb4f3a6b7a7d0c5d8160c2cd69/lightningd/chaintopology.c#L855
    https://github.com/ElementsProject/lightning/blob/a47fd8cf3e1c04fb4f3a6b7a7d0c5d8160c2cd69/lightningd/options.c#L663
    https://github.com/ElementsProject/lightning/blob/a47fd8cf3e1c04fb4f3a6b7a7d0c5d8160c2cd69/lightningd/chaintopology.c#L437
    </details>

- yes, `eclair` does force-close:
    I think they force-close if the feerate is outside a `factor of 8` of what they consider reasonable (which is `"bitcoind 2-block CONSERVATIVE estimate"`).
    <details>
     <summary>source</summary>
    
    https://github.com/ACINQ/eclair/blob/4012db582815e4d77b4cb20831bb11db0e90a6a7/eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala#L369
    https://github.com/ACINQ/eclair/blob/84edf645d0065929baec4c8bd4c3920a41f801f2/eclair-core/src/main/resources/reference.conf#L92
    https://github.com/ACINQ/eclair/blob/84edf645d0065929baec4c8bd4c3920a41f801f2/eclair-core/src/main/resources/reference.conf#L85
    </details>

-----

Of further interest is that Eclair, if the backend is not bitcoind (e.g. on mobile), simply polls a public BitGo API for fee estimates:
https://github.com/ACINQ/eclair/blob/b73030018cc53c69e6950bb8222f8e3db4e0fde3/eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala#L239

**Comment by SomberNight** [comment]
Naturally the question is what we should do.

A simple proposal:
- we already connect to ~10 Electrum servers for block header subscriptions
- instead of only polling the "main server", poll each connected server for fee estimates
- if `auto_connect` is enabled (default):
    - use the median of the received estimates
- if `auto_connect` is disabled, the client is already signalling that they trust the chosen server to some level (it might be their own server!)
    - use fee estimates from "main server" (as in status-quo)

**Comment by TheBlueMatt** [comment]
The other approach, of course, is to help get https://github.com/lightningnetwork/lightning-rfc/pull/688 over the line and then lean on CPFP and never bump the fee at all beyond minimum fee. That is certainly our plan - the entire model around fees in lightning is really terrible.

**Comment by ecdsa** [comment]
@TheBlueMatt we'll use that option when it is available. in the meantime, I am not sure how we can help 

@SomberNight here is a minimal change that implements what yoou describe: 133d74adfb4f5d0401caf50943473b129784b8ae. I really think `fee_estimates_eta` and `mempool_fees` should not be part of `simple_config.py`; we should either move all those methods to network.py, or create a new object for them.

**Comment by TheBlueMatt** [comment]
@ecdsa implementing it now (and cross-checking with other implementations) is sufficient to get it merged and start using it :).

**Comment by ecdsa** [comment]
fixed in 133d74adfb4f5d0401caf50943473b129784b8ae

**Comment by SomberNight** [comment]
@TheBlueMatt 
> The other approach, of course, is to help get lightningnetwork/lightning-rfc#688 over the line and then lean on CPFP and never bump the fee at all beyond minimum fee. That is certainly our plan - the entire model around fees in lightning is really terrible.

What if the mempool is full and so the min mempool acceptance feerate is over the feerate of the commitment tx? How can you broadcast the parent and the child txs together? Is package relay implemented in Bitcoin yet?

**Comment by TheBlueMatt** [comment]
> How can you broadcast the parent and the child txs together? Is package relay implemented in Bitcoin yet?

Not yet, but there is some acive work towards it.

> What if the mempool is full and so the min mempool acceptance feerate is over the feerate of the commitment tx?

This is true, but also isn't really fixed by update_fee. In an update_fee world you can change the fee, but you're always trying to predict what the *block* feerate will be when you need to broadcast it. Doing that programmatically, even an hour out, is really no easier than a developer predicting what the block feerate will be six months out. Even more importantly, however, in an anchor_outputs + no update_fee world, you don't need to predict the *block* feerate, only the *mempool* feerate, which not only is much lower (often by an order of magnitude or more), but far less susceptible to short-term spikes.

**Comment by TheBlueMatt** [comment]
Note that, given these issues, I generally consider current lightning (with update_fee) to be insecure for any real/important value. anchor_outputs, indeed, isn't a complete solution, but its much, much better than the current state, and luckily once we have that no further changes are needed to the lightning protocol, only changes to Bitcoin Core/Bitcoin P2P.
