### ISSUE TITLE
Unverified Inputs - error message when sending from Ledger Nano

### ISSUE THREAD

**Issue by emx0r** [spesmilo/electrum#6230]
When sending BTC transaction from Ledger Nano X, I am getting an error message 
Unverified inputs

- update third party wallet software

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/pull/6198

**Comment by angularly** [comment]
I get the same when using Blockstream Green to send with Nano X. Is it a problem with Ledger Nano X or with the Blockstream app?

**Comment by SomberNight** [comment]
this should be fixed by https://github.com/spesmilo/electrum/pull/6293
forgot to close.

**Comment by JFHCFC** [comment]
Despite updating to the latest versions, the error persists "Unverified inputs"
I cannot transfer bsv to another wallet

I’ve got:

    Electrumsv 1.3.13
    Ledger Live - 2.29.0
    Firmware on Nano S - 2.0.0
    Installed BTC - 1.6.2
    Installed BCH- 1.6.2

**Comment by SomberNight** [comment]
Electrum [only supports Bitcoin](https://electrum.readthedocs.io/en/latest/faq.html#does-electrum-support-altcoins-cryptocurrencies). ElectrumSV is a different project.
