### ISSUE TITLE
ACINQ lightning payment TRAMPOLINE_FEE_INSUFFICIENT

### ISSUE THREAD

**Issue by PanosChtz** [spesmilo/electrum#8297]
I have been using ACINQ trampoline channels and making a lightning payment has been very painful over the last few weeks.
The error I am getting is TRAMPOLINE_FEE_INSUFFICIENT and I don't know how to overcome this, other than keep retrying (sometimes for 20 or even 30 minutes) until the payment gets through. Is there any way to improve lightning payments? Can provide the full log if needed.

**Comment by ecdsa** [comment]
Please provide a log. Also, make sure you are using the latest version of Electrum before reporting an issue.

**Comment by PanosChtz** [comment]
Here is the log about one transaction I was trying to make yesterday
https://pastebin.com/G3mBeZPz
Using Electrum 4.3.4

**Comment by ecdsa** [comment]
Thanks for the log. This was probably a liquidity problem with second trampoline nodes in the chosen routes. The issue is that trampoline nodes return `TRAMPOLINE_FEE_INSUFFICIENT` in a lot of cases, regardless what the actual cause of the error is.

Falling back to a route with a single trampoline node would have avoided that, but our current code does not do that if it receives that error message. It is difficult to decide to do that automatically, because we do not know what users want; it is a tradeoff between privacy and payment reliability. For that reason, I think we should make "use two trampolines" optional, and make that option user-visible. That way, they can try to disable it if their payments fail.

**Comment by ecdsa** [comment]
Note: I have rebalanced some channels on the trampoline, it should work now.

**Comment by PanosChtz** [comment]
Issue persists. I have been trying to make a payment for over an hour, retrying over and over again, and have been getting this error all the time, even with different amounts. I just can't pay with lightning at this point.

**Comment by FiretronP75** [comment]
Using Version 4.4.6 and getting the TRAMPOLINE_FEE_INSUFFICIENT in my logs for failed transactions on Electrum Trampoline. Is it from too many people starting to use lightning after last nights btc fee jump?

**Comment by ecdsa** [comment]
Maybe retry now; I added a few more channels to the server.

**Comment by supertestnet** [comment]
I've been getting this error a lot lately. My initial assumption was that this error means I "offered" my trampoline node a fee of X to pay invoice Y, and they replied my offer of X was not enough. It sounds like this error is not "always" that (because you said "trampoline nodes return TRAMPOLINE_FEE_INSUFFICIENT in a lot of cases, regardless what the actual cause of the error is"). But still, in those cases where the cause *is* that the trampoline node wants a higher fee, could you add a feature so that we can "offer" a higher fee?

Possibly related anecdote regarding a different implementation of LN: when I withdraw money from stacker.news (which uses LND as its backend), I have to paste an invoice and set a maximum fee I'm willing to pay to process this withdrawal. By default, the maximum fee is 10 sats. When I withdraw a larger amount, my transactions often fail with the default max fee, and the interface helpfully informs me that the payment is more likely to succeed if I set a larger max fee for this particular invoice. And they are right, if I "up it" to 100 sats it usually goes through just fine (and the interface often tells me that the fee I paid ended up being in the 20s or 30s).

Could something similar help electrum payments succeed more? Specifically, a field that lets uses increase the max fee they are willing to pay the trampoline node to process this payment? Please consider this a feature request.

**Comment by ecdsa** [comment]
@supertestnet: See #9033 
The new acinq fees are higher than the maximum allowed by Electrum.
We are going to do a new release next week, that will give users control of the max.

**Comment by ecdsa** [comment]
fixed in 4.5.5
