### ISSUE TITLE
Make APK builds reproducible more reliably

### ISSUE THREAD

**Issue by thecockatiel** [spesmilo/electrum#9215]
related to https://github.com/spesmilo/electrum/issues/9210 
opened since it needs its own issue

currently the `.pyc` files in `private.tar` embeds the full path to files, which makes the builds not reproducible when compiled on different paths/environments, which should not be happening

**Comment by SomberNight** [comment]
> currently the .pyc files in private.tar embeds the full path to files

That might be fixed by patching python-for-android here:
https://github.com/SomberNight/python-for-android/blob/5df11be775eadcc19774e5bb118ee407330b8d83/pythonforandroid/recipes/python3/__init__.py#L351
https://github.com/SomberNight/python-for-android/blob/5df11be775eadcc19774e5bb118ee407330b8d83/pythonforandroid/bootstraps/common/build/build.py#L218

See https://docs.python.org/3/library/compileall.html#cmdoption-compileall-s
If we are lucky, we can just add the `-s` flag.

---

Are the `.pyc` files the only difference? In [the other issue](https://github.com/spesmilo/electrum/issues/9210#issuecomment-2375445548) you also mentioned something about the `.so` files.

**Comment by thecockatiel** [comment]
Finally I was able to reproduce the build by using the exact same paths as docker (`/home/user/wspace/electrum`) on the gitlab runner
and yes, the .so files are affected by the same reason

I'm glad I was able to pinpoint the issue after over 100+ builds :D

**Comment by thecockatiel** [comment]
I'm currently in the process of making the needed steps more compact for creating the f-droid MR

**Comment by thecockatiel** [comment]
if we can strip the zero and fix the website url and make a release, that would be a huge help for automating the future releases on f-droid, right now every release needs to be added manually to f-droid, unless either the redirect is there or the version fix is released

**Comment by thecockatiel** [comment]
hmm, can you try patching it on your side to see if it strips the unnecessary paths ? (each build takes ~2h on gitlab and +4h on my pc)
the path is easy to find in `main.pyc` in the private.tar when opened in a text editor

**Comment by SomberNight** [comment]
> hmm, can you try patching it on your side to see if it strips the unnecessary paths ?
> the path is easy to find in main.pyc in the private.tar when opened in a text editor

I think I fixed the `pyc` issue with https://github.com/spesmilo/electrum/commit/2c6e768c8dc0fef5d01b3bb90fdff6600eb719db.

Not sure about the .so files or other differences, I did not have time to look at those. The above change only affects the pyc-generation.

**Comment by thecockatiel** [comment]
if it fixes pyc, it should probably also fix so files I guess
do you want to make a release ? that way I can verify it against your build

**Comment by thecockatiel** [comment]
some stuff I tried removing and the build is still reproducible (comparing to Dockerfile):
- removed `USE_SDK_WRAPPER` and `GRADLE_OPTS` envs
- removed manual ANT installation
- skipped user altogether (user name is vagrant on f-droid build server image with id 1000)
- removed `locales` package and language envs
- combined all apt installs except for the one before replacing apt sources

**Comment by thecockatiel** [comment]
It seems like NDK path is also affecting the builds, specifically its affecting the .so files. I have no idea whats going on there.

**Comment by thecockatiel** [comment]
how does the build decide to include a file in `private.tar` or not ?
do we need to make some change to ignore the fastlane folder ? 
I'm asking because I was ending up with my build log inside the tar file

**Comment by SomberNight** [comment]
Is the fastlane folder getting included in the apk?

See the buildozer `.spec` file, e.g.:
https://github.com/spesmilo/electrum/blob/6d593e3373888eb5ec55fa1fe487a4106f23692a/contrib/android/buildozer_qml.spec#L21-L22
and [`contrib/android/blacklist.txt`](https://github.com/spesmilo/electrum/blob/6d593e3373888eb5ec55fa1fe487a4106f23692a/contrib/android/blacklist.txt)

**Comment by thecockatiel** [comment]
I think yes, but I haven't tested. I asked because of that exactly

**Comment by thecockatiel** [comment]
It seems we have to disable some stuff in android gradle settings:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15858#note_2150822234
https://gitlab.com/fdroid/fdroidserver/-/issues/1056#note_1218193185

**Comment by thecockatiel** [comment]
hey @SomberNight , sorry about the mention, can you take a look at the fdroid MR comment?

**Comment by SomberNight** [comment]
Ok, done in https://github.com/spesmilo/electrum/commit/071150f4656942602856ec782554a80dfdd35f7b

I've also sent a patch upstream (https://github.com/kivy/python-for-android/pull/3069).

**Comment by thecockatiel** [comment]
let's keep this one open till the next f-droid MR with auto updates enabled is merged

**Comment by SomberNight** [comment]
note: version 4.5.6 is now released

**Comment by thecockatiel** [comment]
thanks for letting me know
I'll create a MR soon

**Comment by thecockatiel** [comment]
It seems the build is still sensitive to paths
I tried building without moving the files, and it still does not match (both .so files and private.tar)
inside the private.tar there's only 2 files that don't match:
```
-      12134 467e12c6 packages/QtPy-2.4.1.dist-info/RECORD
+      12134 734ba192 packages/QtPy-2.4.1.dist-info/RECORD
+      45931 9504828a packages/pip-22.3.1.dist-info/RECORD
-      45931 a8ce1712 packages/pip-22.3.1.dist-info/RECORD
```
I tried looking inside, and the lines that differ are only the top lines where there's a hash. for example for the pip one:
![image](https://github.com/user-attachments/assets/aff475fd-b35d-4db4-ad0b-80643312d898)

the only good news is the file names are no longer absolute inside the pyc files with the change you made before, so they don't mismatch

I'm doing a rebuild with the same paths as before, I'll let you know if anything else goes wrong.

**Comment by thecockatiel** [comment]
created the MR: 
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16048

**Comment by thecockatiel** [comment]
also it seems Electrum 4.5.5.0 has been released on f-droid!
thanks a lot for your collaboration!

**Comment by thecockatiel** [comment]
the new version also merged.
thank you @SomberNight
